# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:

  # Python dependencies managed by pip
  - package-ecosystem: pip
    directory: "/"
    versioning-strategy: "increase-if-necessary"
    schedule:
      interval: weekly
      day: "sunday"
      time: "06:00"
      timezone: "Europe/Paris"
    labels:
      - "dependencies"
      - "python"
    assignees:
      - "tristiisch"

  - package-ecosystem: docker
    directory: "/"
    versioning-strategy: "increase"
    schedule:
      interval: monthly
      time: "06:00"
      timezone: "Europe/Paris"
    labels:
      - "dependencies"
      - "docker"
    assignees:
      - "tristiisch"

  - package-ecosystem: github-actions
    directory: "/"
    versioning-strategy: "increase"
    schedule:
      interval: monthly
      time: "06:00"
      timezone: "Europe/Paris"
    labels:
      - "dependencies"
      - "ci"
    assignees:
      - "tristiisch"
