services:
  discord:
    build:
      dockerfile: ./.docker/Dockerfile
      target: executable-dev
      context: .
    restart: no
    volumes:
      - ./src:/app/src
      - ./logs:/app/logs
      - ./songs:/app/songs
    networks:
      - pyramid_network
    ports:
      - 5678:5678
      - 5679:5679
    env_file: .env

networks:
   pyramid_network:
    driver: bridge
