services:
  discord:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./logs:/app/logs
      - ./songs:/app/songs
    networks:
      - pyramid_network
    env_file: .env

networks:
   pyramid_network:
    driver: bridge
