version: '3.7'

services:
  pyramid:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pyramid
    hostname: pyramid
    restart: always
    volumes:
      - ./logs:/app/logs
      - ./songs:/app/songs
    networks:
      - pyramid_network
    env_file: .env

networks:
   pyramid_network:
    driver: bridge
