version: '3.7'

services:
  discord:
    image: tristiisch/pyramid:latest
    restart: always
    volumes:
      - ./docker/pyramid/logs:/app/logs
      - ./docker/pyramid/songs:/app/songs
    env_file: .env
