version: '3.7'
name: 'pyramid-dev'

services:

  pyramid:
    # image: tristiisch/pyramid:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: .\.docker\pyramid\logs
        target: /app/logs
        bind:
          create_host_path: true
      - type: bind
        source: .\.docker\pyramid\songs
        target: /app/songs
        bind:
          create_host_path: true
    depends_on:
      postgreSQL:
        condition: service_healthy
    restart: always
    ports:
    - 49149:49150
    networks:
    - pyramid_network
    container_name : pyramid
    hostname: pyramid
    env_file: .env

  postgreSQL:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-bob}
      PGDATA: /data/postgres
    volumes:
      - type: bind
        source: .\.docker\postgres_data
        target: /data/postgres
        bind:
          selinux: Z
          create_host_path: true
    restart: always
    ports:
    - ${POSTGRES_PORT-5432}:5432
    networks:
    - pyramid_network
    container_name : postgreSQL
    hostname: postgreSQL
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      # Docker Engine version 25.0
      # start_period: 30s
      # start_interval: 1s

      interval: 1s
      timeout: 5s
      retries: 60

networks:
   pyramid_network:
    driver: bridge
