version: '3.8'

services:
  pyramid:
    image: tristiisch/pyramid:pre-prod
    volumes:
      - pyramid_logs_preprod:/app/logs
      - pyramid_songs_preprod:/app/songs
    environment:
      MODE: pre-production
      GENERAL__LIMIT_TRACKS: 100
      DISCORD__FFMPEG: /usr/bin/ffmpeg
      DEEZER__FOLDER: ./songs
    deploy:
      mode: replicated
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 30s
      rollback_config:
        parallelism: 1
        delay: 0s
        failure_action: pause
        monitor: 5s
        order: start-first
      update_config:
        parallelism: 1
        delay: 30s
        failure_action: pause
        monitor: 5s
        order: start-first

volumes:
  pyramid_logs_preprod:
  pyramid_songs_preprod:
