version: '3.7'

services:

  pyramid:
    image: tristiisch/pyramid:latest
    volumes:
    - ./config.yml:/app/config.yml
    - ./logs:/app/logs
    - ./songs:/app/songs
    restart: always
    networks:
    - pyramid_network
    container_name : pyramid
    hostname: pyramid

networks:
   pyramid_network:
    driver: bridge
