version: '3.7'
name: 'pyramid-dev'

services:

  pyramid:
    # image: tristiisch/pyramid:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: .\.docker\pyramid\logs
        target: /app/logs
        bind:
          create_host_path: true
      - type: bind
        source: .\.docker\pyramid\songs
        target: /app/songs
        bind:
          create_host_path: true
    restart: always
    ports:
    - 49149:49150
    networks:
    - pyramid_network
    container_name : pyramid
    hostname: pyramid
    env_file: .env

networks:
   pyramid_network:
    driver: bridge
