version: '3.8'

services:
  discord:
    image: tristiisch/pyramid:latest
    volumes:
      - pyramid_logs_prod:/app/logs
      - pyramid_songs_prod:/app/songs
    environment:
      MODE: production
      GENERAL__LIMIT_TRACKS: 100
      DISCORD__FFMPEG: /usr/bin/ffmpeg
      DEEZER__FOLDER: ./songs
    secrets:
      - PYRAMID_PROD
    deploy:
      mode: replicated
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 30s
      rollback_config:
        parallelism: 1
        delay: 0s
        failure_action: pause
        monitor: 5s
        order: start-first
      update_config:
        parallelism: 1
        delay: 30s
        failure_action: pause
        monitor: 5s
        order: start-first

volumes:
  pyramid_logs_prod:
  pyramid_songs_prod:

secrets:
  PYRAMID_PROD:
    external: true
