name: Python 3.11 CI

on:
  push:
    branches:
      - "*"
    paths:
      - "src/**/*.py"
      - "requirements.txt"
  pull_request:
    branches:
      - "*"
    paths:
      - "src/**/*.py"
      - "requirements.txt"

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
            path: ~/.cache/pip
            key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
            restore-keys: |
              ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Test compilation
        run: |
          python -m compileall .

  docker_push:
    needs: compile
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get Git Commit Details
        run: |
          commit_id=$(git log -1 --pretty=%H)
          commit_id_short=$(echo "$commit_id" | cut -c1-8)
          echo "{
            \"commit_id\": \"$commit_id_short\",
            \"branch\": \"$(git rev-parse --abbrev-ref HEAD)\",
            \"last_author\": \"$(git log -1 --pretty=%an)\"
          }" > git_info.json
          echo "commit_id=$commit_id" >> $GITHUB_OUTPUT
        id: set_git_info

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set Docker Tag
        run: |
          if [ ${{ github.ref }} = 'refs/heads/main' ]; then
            echo "tag=latest" >> $GITHUB_OUTPUT
          elif [ ${{ github.ref }} = 'refs/heads/dev' ]; then
            echo "tag=pre-prod" >> $GITHUB_OUTPUT
          else
            echo "tag=skip" >> $GITHUB_OUTPUT
          fi
        id: set_tag

      - name: Build and push
        if: steps.set_tag.outputs.tag != 'skip'
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/pyramid:${{ steps.set_tag.outputs.tag }}, ${{ secrets.DOCKERHUB_USERNAME }}/pyramid:${{ steps.set_git_info.outputs.commit_id }}
