name: Improve code

on:
  push:
    branches:
      - "*"
    # paths:
    #   - "src/**/*.py"
    #   - "requirements.txt"
  pull_request:
    types: [opened, synchronize]
    # paths:
    #   - "src/**/*.py"
    #   - "requirements.txt"
  workflow_dispatch:

jobs:

  commit_to_pr:
    runs-on: ubuntu-latest
    name: "Improve and format code"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fix code quality
        uses: chartboost/ruff-action@v1
        with:
          src: "./src"
          args: check --fix

      - name: Add changes code quality
        run: git add **/*.py

      - name: Check for changes code quality
        run: |
          if ! git diff --quiet --cached; then
            echo "There are changes to commit."
            echo "has_changes=true" >> $GITHUB_OUTPUT
          else
            echo "No changes to commit."
            echo "has_changes=false" >> $GITHUB_OUTPUT
          fi
        id: check_changes_quality

      - name: Commit changes code quality
        if: steps.check_changes_quality.outputs.has_changes == 'true'
        run: |
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          git commit -m "[ruff] Improve code quality"

      - name: Fix code format
        uses: chartboost/ruff-action@v1
        with:
          src: "./src"
          args: format

      - name: Add changes format
        run: git add **/*.py

      - name: Check for changes code quality
        run: |
          if ! git diff --quiet --cached; then
            echo "There are changes to commit."
            echo "has_changes=true" >> $GITHUB_OUTPUT
          else
            echo "No changes to commit."
            echo "has_changes=false" >> $GITHUB_OUTPUT
          fi
        id: check_changes_format

      - name: Commit code format
        if: steps.check_changes_format.outputs.has_changes == 'true'
        run: |
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          git add **/*.py
          git commit -m "[ruff] Improve code format"

    # Only in PR
      - name: Push changes in pull request
        if: ${{ github.event_name == 'pull_request' && (steps.check_changes_quality.outputs.has_changes == 'true' || steps.check_changes_format.outputs.has_changes == 'true') }}
        run: |
          git push origin HEAD:refs/heads/${{ github.head_ref }}

    # Only in Push
      - name: Check for existing pull request
        if: ${{ github.event_name == 'push' && !startsWith(github.head_ref, 'pull') && (steps.check_changes_quality.outputs.has_changes == 'true' || steps.check_changes_format.outputs.has_changes == 'true') }}
        run: |
          if [[ $(gh pr list -s open -H auto-improve/${{ github.ref }}) ]]; then
            gh pr close auto-improve/${{ github.ref }} -c "An other PR has been created"
          fi

      - name: Create Pull Request
        if: ${{ github.event_name == 'push' && !startsWith(github.head_ref, 'pull') && (steps.check_changes_quality.outputs.has_changes == 'true' || steps.check_changes_format.outputs.has_changes == 'true') }}
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Auto improve format"
          title: "[ruff] Auto improve format"
          body: "This is an automatically generated pull request to improve the format."
          branch: auto-improve/${{ github.ref }}
        #   author: "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"
